name: Update README 2
on:
  schedule:
    # Runs every hour
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  # update-readme-with-youtube:
  build:
    name: Update profile README 2
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
      uses: actions/checkout@v4

      - name: Update README
      uses: gautamkrishnar/blog-post-workflow@v1
